num_workers: 4
learning_rate: 0.0005
optim: adam
weight_decay: 0.01
clamp: 0.8
loss_function: Huber # MSE
normed_loss: False

data_stride: 3

model:
  t_in: 12
  t_out: 12
  kNN: 6
  interval: 6
  num_blocks: 5
  num_layers: 25
  CG_iters: 3
  PGD_iters: 3
  num_heads: 4
  feature_channels: 6
  use_extrapolation: True
  use_one_channel: True
  sharedM: False
  sharedQ: False
  diff_interval: True

ADMM_params:
  mu_u: 3
  mu_d1: 3
  mu_d2: 3

st_emb_info:
  spatial_dim: 5
  t_dim: 10
  tid_dim: 6
  diw_dim: 4

