num_workers: 4
learning_rate: 0.0005
optim: adamw
weight_decay: 0.01
clamp: 0.8
loss_function: Huber
normed_loss: False

data_stride: 3

model:
  t_in: 12
  t_out: 12
  kNN: 4
  interval: 4
  num_blocks: 5
  num_layers: 25
  CG_iters: 3
  PGD_iters: 3
  num_heads: 4
  feature_channels: 6
  use_extrapolation: True
  use_one_channel: True
  shared_params: False

ADMM_params:
  mu_u: 3
  mu_d1: 3
  mu_d2: 3

