num_workers: 4
learning_rate: 0.001
optim: adamw
weight_decay: 0.01
clamp: 0.8
loss_function: MSE
normed_loss: False

data_stride: 1

model:
  t_in: 10
  t_out: 5
  kNN: 6
  interval: 5
  num_blocks: 3
  num_layers: 30
  CG_iters: 3
  PGD_iters: 3
  num_heads: 4
  feature_channels: 6
  use_extrapolation: True
  use_one_channel: True
  sharedM: False
  sharedQ: True
  diff_interval: True

ADMM_params:
  mu_u: 3
  mu_d1: 3
  mu_d2: 3

st_emb_info:
  spatial_dim: 5
  t_dim: 6
  tid_dim: 4
  diw_dim: 0

